apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres
spec:
  storageClassName: hostpath # TODO: make configurable via values.yaml
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # TODO: make configurable via values.yaml
