on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'aws/**'

jobs:
  taskcat:
    name: Execute TaskCat Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install TaskCat
        run: |
          pip install taskcat

      - name: Run TaskCat
        run: |
          taskcat test run --project-root aws/
